allow a list of files for backups

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,11 +1,22 @@
 #!/bin/bash
 
+# exit when any command fails
+set -e
+set -o pipefail
+
+usage () {
+	echo ""
+	echo "Try 'backup --help' for more information"
+	exit 1
+}
+
 # assumes that the veracrypt encrypted volume has been already created 
 
 # where the veracrypt encrypted volume will be mounted
-mount_point=
+MOUNT_POINT=
 
 # mount the encrypted veracrypt volume
+
 
 # =====================================
 # BACKUP ALGO
@@ -14,18 +25,33 @@ mount_point=
 BACKUP_LOCATION=./test/backup
 
 # list of all files and folders in the backup
-FILES=./test/files
+FILES=(
+	"./test/docs"
+	"./test/vids"
+	"./test/photos"
+)
 
-# check if directories exist
+if [ ! -d "$BACKUP_LOCATION" ]; then
+	echo "Backup location '"$BACKUP_LOCATION"' does not exist.">&2
+	usage
+fi
+
+for file in "${FILES[@]}"; do
+	if [ ! -d "$file" ]; then
+		echo "Files "$file" do not exist.">&2
+		usage
+	fi
+done
 
 
 # collect and compress the list of files onto the $backup_location/YYYY-MM-dd-HHmmss_backup
 backup_filename=".$(date +%F-%H%M%S)_backup"
 
-# perform full backup with tar and gzip
-echo "Backup process started."
-tar czvf "$BACKUP_LOCATION"/"$backup_filename" "$FILES"
-echo "Backup completed successfully."
+echo "Full backup started."
+
+tar czvf "$BACKUP_LOCATION"/"$backup_filename".tgz ${FILES[*]}
+
+echo "Full backup completed successfully."
 
 
 # =====================================
